parameters:
    piapp.manager.formbuilder.model.snippet.class: Sfynx\CmfBundle\Manager\FormBuilder\PiModelWidgetSnippet   
    piapp.manager.formbuilder.model.breadcrumb.class: Sfynx\CmfBundle\Manager\FormBuilder\PiModelWidgetBreadcrumb   
    piapp.manager.formbuilder.model.connexion.class: Sfynx\CmfBundle\Manager\FormBuilder\PiModelWidgetConnexion
    piapp.manager.formbuilder.model.reset.class: Sfynx\CmfBundle\Manager\FormBuilder\PiModelWidgetReset
    
services:
    #
    # configuration of the FORM BUILDER services
    #
    pi_app_admin.formbuilder_manager.model.snippet:
        class: %piapp.manager.formbuilder.model.snippet.class%
        arguments: ['@service_container']                
        
    pi_app_admin.formbuilder_manager.model.breadcrumb:
        class: %piapp.manager.formbuilder.model.breadcrumb.class%
        arguments: ['@service_container']  
        
    pi_app_admin.formbuilder_manager.model.connexion:
        class: %piapp.manager.formbuilder.model.connexion.class%
        arguments: ['@service_container']             

    pi_app_admin.formbuilder_manager.model.reset:
        class: %piapp.manager.formbuilder.model.reset.class%
        arguments: ['@service_container'] 